//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GpsMemService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://www.gps.binhanh.com.vn/types/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GpsMemService.VehicleLocationRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GpsMemService.VehicleExtendRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GpsMemService.VehicleIndexRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GpsMemService.VehilceOnlineRequest))]
    public partial class RequestBase : object
    {
        
        private string AccessTokenField;
        
        private string ClientTagField;
        
        private string RequestIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken
        {
            get
            {
                return this.AccessTokenField;
            }
            set
            {
                this.AccessTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientTag
        {
            get
            {
                return this.ClientTagField;
            }
            set
            {
                this.ClientTagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleLocationRequest", Namespace="http://www.gps.binhanh.com.vn/types/")]
    public partial class VehicleLocationRequest : GpsMemService.RequestBase
    {
        
        private GpsMemService.VehicleLocation localField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GpsMemService.VehicleLocation local
        {
            get
            {
                return this.localField;
            }
            set
            {
                this.localField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleExtendRequest", Namespace="http://www.gps.binhanh.com.vn/types/")]
    public partial class VehicleExtendRequest : GpsMemService.RequestBase
    {
        
        private GpsMemService.VehicleExtend extField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GpsMemService.VehicleExtend ext
        {
            get
            {
                return this.extField;
            }
            set
            {
                this.extField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleIndexRequest", Namespace="http://www.gps.binhanh.com.vn/types/")]
    public partial class VehicleIndexRequest : GpsMemService.RequestBase
    {
        
        private bool ChangeReportField;
        
        private int CompanyIDNewField;
        
        private int CompanyIDOldField;
        
        private string VehiclePlaceField;
        
        private int XNCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ChangeReport
        {
            get
            {
                return this.ChangeReportField;
            }
            set
            {
                this.ChangeReportField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyIDNew
        {
            get
            {
                return this.CompanyIDNewField;
            }
            set
            {
                this.CompanyIDNewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyIDOld
        {
            get
            {
                return this.CompanyIDOldField;
            }
            set
            {
                this.CompanyIDOldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehiclePlace
        {
            get
            {
                return this.VehiclePlaceField;
            }
            set
            {
                this.VehiclePlaceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XNCode
        {
            get
            {
                return this.XNCodeField;
            }
            set
            {
                this.XNCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehilceOnlineRequest", Namespace="http://www.gps.binhanh.com.vn/types/")]
    public partial class VehilceOnlineRequest : GpsMemService.RequestBase
    {
        
        private string ArrayVehicleIDsField;
        
        private int[] AryGroupIdField;
        
        private string BKSField;
        
        private int CompanyIDField;
        
        private System.DateTime LastTimeField;
        
        private int OldCompanyIdField;
        
        private long VehicleIDField;
        
        private int XNCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArrayVehicleIDs
        {
            get
            {
                return this.ArrayVehicleIDsField;
            }
            set
            {
                this.ArrayVehicleIDsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] AryGroupId
        {
            get
            {
                return this.AryGroupIdField;
            }
            set
            {
                this.AryGroupIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BKS
        {
            get
            {
                return this.BKSField;
            }
            set
            {
                this.BKSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyID
        {
            get
            {
                return this.CompanyIDField;
            }
            set
            {
                this.CompanyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastTime
        {
            get
            {
                return this.LastTimeField;
            }
            set
            {
                this.LastTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OldCompanyId
        {
            get
            {
                return this.OldCompanyIdField;
            }
            set
            {
                this.OldCompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long VehicleID
        {
            get
            {
                return this.VehicleIDField;
            }
            set
            {
                this.VehicleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XNCode
        {
            get
            {
                return this.XNCodeField;
            }
            set
            {
                this.XNCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleLocation", Namespace="http://www.gps.binhanh.com.vn/types/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GpsMemService.VehicleExtend))]
    public partial class VehicleLocation : GpsMemService.VehicleBase
    {
        
        private string DriverLicenseField;
        
        private string DriverLicenseUDPField;
        
        private string DriverNameField;
        
        private string DriverNameUDPField;
        
        private int DrivingTimeField;
        
        private System.DateTime ImgCaptureTimeField;
        
        private int ImgChannelField;
        
        private string ImgImageLinkField;
        
        private double ImgLatitudeField;
        
        private double ImgLongitudeField;
        
        private double SOSLatitudeField;
        
        private double SOSLongitudeField;
        
        private System.DateTime SOSTimeField;
        
        private double TotalKmField;
        
        private string VehiclePlateField;
        
        private int XNCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriverLicense
        {
            get
            {
                return this.DriverLicenseField;
            }
            set
            {
                this.DriverLicenseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriverLicenseUDP
        {
            get
            {
                return this.DriverLicenseUDPField;
            }
            set
            {
                this.DriverLicenseUDPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriverName
        {
            get
            {
                return this.DriverNameField;
            }
            set
            {
                this.DriverNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriverNameUDP
        {
            get
            {
                return this.DriverNameUDPField;
            }
            set
            {
                this.DriverNameUDPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DrivingTime
        {
            get
            {
                return this.DrivingTimeField;
            }
            set
            {
                this.DrivingTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ImgCaptureTime
        {
            get
            {
                return this.ImgCaptureTimeField;
            }
            set
            {
                this.ImgCaptureTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImgChannel
        {
            get
            {
                return this.ImgChannelField;
            }
            set
            {
                this.ImgChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImgImageLink
        {
            get
            {
                return this.ImgImageLinkField;
            }
            set
            {
                this.ImgImageLinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ImgLatitude
        {
            get
            {
                return this.ImgLatitudeField;
            }
            set
            {
                this.ImgLatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ImgLongitude
        {
            get
            {
                return this.ImgLongitudeField;
            }
            set
            {
                this.ImgLongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SOSLatitude
        {
            get
            {
                return this.SOSLatitudeField;
            }
            set
            {
                this.SOSLatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SOSLongitude
        {
            get
            {
                return this.SOSLongitudeField;
            }
            set
            {
                this.SOSLongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SOSTime
        {
            get
            {
                return this.SOSTimeField;
            }
            set
            {
                this.SOSTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalKm
        {
            get
            {
                return this.TotalKmField;
            }
            set
            {
                this.TotalKmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehiclePlate
        {
            get
            {
                return this.VehiclePlateField;
            }
            set
            {
                this.VehiclePlateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XNCode
        {
            get
            {
                return this.XNCodeField;
            }
            set
            {
                this.XNCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleBase", Namespace="http://www.gps.binhanh.com.vn/types/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GpsMemService.VehicleLocation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GpsMemService.VehicleExtend))]
    public partial class VehicleBase : object
    {
        
        private string AddressField;
        
        private string DataExtendsField;
        
        private System.DateTime DbTimeField;
        
        private short DirectionField;
        
        private System.DateTime GpsTimeField;
        
        private System.DateTime LastTimeMoveField;
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        private int StateField;
        
        private long VehicleIDField;
        
        private System.DateTime VehicleTimeField;
        
        private int VelocityGPSField;
        
        private int VelocityMechanicalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataExtends
        {
            get
            {
                return this.DataExtendsField;
            }
            set
            {
                this.DataExtendsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DbTime
        {
            get
            {
                return this.DbTimeField;
            }
            set
            {
                this.DbTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Direction
        {
            get
            {
                return this.DirectionField;
            }
            set
            {
                this.DirectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GpsTime
        {
            get
            {
                return this.GpsTimeField;
            }
            set
            {
                this.GpsTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastTimeMove
        {
            get
            {
                return this.LastTimeMoveField;
            }
            set
            {
                this.LastTimeMoveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long VehicleID
        {
            get
            {
                return this.VehicleIDField;
            }
            set
            {
                this.VehicleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VehicleTime
        {
            get
            {
                return this.VehicleTimeField;
            }
            set
            {
                this.VehicleTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VelocityGPS
        {
            get
            {
                return this.VelocityGPSField;
            }
            set
            {
                this.VelocityGPSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VelocityMechanical
        {
            get
            {
                return this.VelocityMechanicalField;
            }
            set
            {
                this.VelocityMechanicalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleExtend", Namespace="http://www.gps.binhanh.com.vn/types/")]
    public partial class VehicleExtend : GpsMemService.VehicleLocation
    {
        
        private string AccountantField;
        
        private double AccumulateKmGpsField;
        
        private double AccumulateKmMechanicalField;
        
        private int[] AryGroupIDField;
        
        private double BatteryField;
        
        private int CompanyIdField;
        
        private int DataExtField;
        
        private string DealerField;
        
        private short DoorCountField;
        
        private System.DateTime ExpireDateField;
        
        private int FlagsField;
        
        private short IconCodeField;
        
        private bool IsDeletedField;
        
        private bool IsDuplicateIMEIField;
        
        private bool IsLockedField;
        
        private bool IsLockedBAPField;
        
        private bool IsReaderUpdateField;
        
        private bool IsShowField;
        
        private bool IsUDPUpdateField;
        
        private bool IsVehiclePlateChangedField;
        
        private System.DateTime JoinSystemDateField;
        
        private System.DateTime MCExpriedField;
        
        private System.DateTime MCExtendField;
        
        private int MessageIdBAPField;
        
        private System.Nullable<int> MinuteManchineOnField;
        
        private int MinuteStopOfManchineOnField;
        
        private string ModernField;
        
        private string PrivateCodeField;
        
        private System.DateTime ReaderUpdateDateField;
        
        private string ReasonOfLockedField;
        
        private string SellerField;
        
        private short SpeedOverCountField;
        
        private short StopCountField;
        
        private int StopTimeField;
        
        private double TotalKmMechanicalField;
        
        private int TotalMinuteStopOfManchineOnField;
        
        private System.DateTime UDPUpdateDateField;
        
        private string VehicleGroupIDsField;
        
        private int VehicleTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Accountant
        {
            get
            {
                return this.AccountantField;
            }
            set
            {
                this.AccountantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AccumulateKmGps
        {
            get
            {
                return this.AccumulateKmGpsField;
            }
            set
            {
                this.AccumulateKmGpsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AccumulateKmMechanical
        {
            get
            {
                return this.AccumulateKmMechanicalField;
            }
            set
            {
                this.AccumulateKmMechanicalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] AryGroupID
        {
            get
            {
                return this.AryGroupIDField;
            }
            set
            {
                this.AryGroupIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Battery
        {
            get
            {
                return this.BatteryField;
            }
            set
            {
                this.BatteryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyId
        {
            get
            {
                return this.CompanyIdField;
            }
            set
            {
                this.CompanyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataExt
        {
            get
            {
                return this.DataExtField;
            }
            set
            {
                this.DataExtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dealer
        {
            get
            {
                return this.DealerField;
            }
            set
            {
                this.DealerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short DoorCount
        {
            get
            {
                return this.DoorCountField;
            }
            set
            {
                this.DoorCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpireDate
        {
            get
            {
                return this.ExpireDateField;
            }
            set
            {
                this.ExpireDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Flags
        {
            get
            {
                return this.FlagsField;
            }
            set
            {
                this.FlagsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IconCode
        {
            get
            {
                return this.IconCodeField;
            }
            set
            {
                this.IconCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDuplicateIMEI
        {
            get
            {
                return this.IsDuplicateIMEIField;
            }
            set
            {
                this.IsDuplicateIMEIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLocked
        {
            get
            {
                return this.IsLockedField;
            }
            set
            {
                this.IsLockedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLockedBAP
        {
            get
            {
                return this.IsLockedBAPField;
            }
            set
            {
                this.IsLockedBAPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReaderUpdate
        {
            get
            {
                return this.IsReaderUpdateField;
            }
            set
            {
                this.IsReaderUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsShow
        {
            get
            {
                return this.IsShowField;
            }
            set
            {
                this.IsShowField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUDPUpdate
        {
            get
            {
                return this.IsUDPUpdateField;
            }
            set
            {
                this.IsUDPUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVehiclePlateChanged
        {
            get
            {
                return this.IsVehiclePlateChangedField;
            }
            set
            {
                this.IsVehiclePlateChangedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime JoinSystemDate
        {
            get
            {
                return this.JoinSystemDateField;
            }
            set
            {
                this.JoinSystemDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MCExpried
        {
            get
            {
                return this.MCExpriedField;
            }
            set
            {
                this.MCExpriedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MCExtend
        {
            get
            {
                return this.MCExtendField;
            }
            set
            {
                this.MCExtendField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageIdBAP
        {
            get
            {
                return this.MessageIdBAPField;
            }
            set
            {
                this.MessageIdBAPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MinuteManchineOn
        {
            get
            {
                return this.MinuteManchineOnField;
            }
            set
            {
                this.MinuteManchineOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinuteStopOfManchineOn
        {
            get
            {
                return this.MinuteStopOfManchineOnField;
            }
            set
            {
                this.MinuteStopOfManchineOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modern
        {
            get
            {
                return this.ModernField;
            }
            set
            {
                this.ModernField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrivateCode
        {
            get
            {
                return this.PrivateCodeField;
            }
            set
            {
                this.PrivateCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReaderUpdateDate
        {
            get
            {
                return this.ReaderUpdateDateField;
            }
            set
            {
                this.ReaderUpdateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonOfLocked
        {
            get
            {
                return this.ReasonOfLockedField;
            }
            set
            {
                this.ReasonOfLockedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seller
        {
            get
            {
                return this.SellerField;
            }
            set
            {
                this.SellerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short SpeedOverCount
        {
            get
            {
                return this.SpeedOverCountField;
            }
            set
            {
                this.SpeedOverCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short StopCount
        {
            get
            {
                return this.StopCountField;
            }
            set
            {
                this.StopCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StopTime
        {
            get
            {
                return this.StopTimeField;
            }
            set
            {
                this.StopTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalKmMechanical
        {
            get
            {
                return this.TotalKmMechanicalField;
            }
            set
            {
                this.TotalKmMechanicalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalMinuteStopOfManchineOn
        {
            get
            {
                return this.TotalMinuteStopOfManchineOnField;
            }
            set
            {
                this.TotalMinuteStopOfManchineOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UDPUpdateDate
        {
            get
            {
                return this.UDPUpdateDateField;
            }
            set
            {
                this.UDPUpdateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleGroupIDs
        {
            get
            {
                return this.VehicleGroupIDsField;
            }
            set
            {
                this.VehicleGroupIDsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VehicleType
        {
            get
            {
                return this.VehicleTypeField;
            }
            set
            {
                this.VehicleTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://www.gps.binhanh.com.vn/types/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GpsMemService.VehicleLocationResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GpsMemService.VehicleExtendResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GpsMemService.VehicleIndexResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GpsMemService.VehicleOnlineResponse))]
    public partial class ResponseBase : object
    {
        
        private GpsMemService.AcknowledgeType AcknowledgeField;
        
        private string BuildField;
        
        private string CorrelationIdField;
        
        private string MessageField;
        
        private System.DateTime ReservationExpiresField;
        
        private string ReservationIdField;
        
        private int RowsAffectedField;
        
        private string VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GpsMemService.AcknowledgeType Acknowledge
        {
            get
            {
                return this.AcknowledgeField;
            }
            set
            {
                this.AcknowledgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Build
        {
            get
            {
                return this.BuildField;
            }
            set
            {
                this.BuildField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorrelationId
        {
            get
            {
                return this.CorrelationIdField;
            }
            set
            {
                this.CorrelationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReservationExpires
        {
            get
            {
                return this.ReservationExpiresField;
            }
            set
            {
                this.ReservationExpiresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationId
        {
            get
            {
                return this.ReservationIdField;
            }
            set
            {
                this.ReservationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsAffected
        {
            get
            {
                return this.RowsAffectedField;
            }
            set
            {
                this.RowsAffectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleLocationResponse", Namespace="http://www.gps.binhanh.com.vn/types/")]
    public partial class VehicleLocationResponse : GpsMemService.ResponseBase
    {
        
        private int StateUpdateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateUpdate
        {
            get
            {
                return this.StateUpdateField;
            }
            set
            {
                this.StateUpdateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleExtendResponse", Namespace="http://www.gps.binhanh.com.vn/types/")]
    public partial class VehicleExtendResponse : GpsMemService.ResponseBase
    {
        
        private int StateUpdateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateUpdate
        {
            get
            {
                return this.StateUpdateField;
            }
            set
            {
                this.StateUpdateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleIndexResponse", Namespace="http://www.gps.binhanh.com.vn/types/")]
    public partial class VehicleIndexResponse : GpsMemService.ResponseBase
    {
        
        private bool StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleOnlineResponse", Namespace="http://www.gps.binhanh.com.vn/types/")]
    public partial class VehicleOnlineResponse : GpsMemService.ResponseBase
    {
        
        private GpsMemService.VehicleExtend[] OnlinesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GpsMemService.VehicleExtend[] Onlines
        {
            get
            {
                return this.OnlinesField;
            }
            set
            {
                this.OnlinesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcknowledgeType", Namespace="http://www.gps.binhanh.com.vn/types/")]
    public enum AcknowledgeType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GpsMemService.ISyncSystemService")]
    public interface ISyncSystemService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSystemService/InitOnlineVerhicle", ReplyAction="http://tempuri.org/ISyncSystemService/InitOnlineVerhicleResponse")]
        System.Threading.Tasks.Task<GpsMemService.VehicleOnlineResponse> InitOnlineVerhicleAsync(GpsMemService.VehilceOnlineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSystemService/GetOnlineVerhicle", ReplyAction="http://tempuri.org/ISyncSystemService/GetOnlineVerhicleResponse")]
        System.Threading.Tasks.Task<GpsMemService.VehicleOnlineResponse> GetOnlineVerhicleAsync(GpsMemService.VehilceOnlineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSystemService/GetSynOnlineVehicle", ReplyAction="http://tempuri.org/ISyncSystemService/GetSynOnlineVehicleResponse")]
        System.Threading.Tasks.Task<GpsMemService.VehicleOnlineResponse> GetSynOnlineVehicleAsync(GpsMemService.VehilceOnlineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSystemService/GetOneOnlineVerhicle", ReplyAction="http://tempuri.org/ISyncSystemService/GetOneOnlineVerhicleResponse")]
        System.Threading.Tasks.Task<GpsMemService.VehicleOnlineResponse> GetOneOnlineVerhicleAsync(GpsMemService.VehilceOnlineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSystemService/UpdateVehicleLocation", ReplyAction="http://tempuri.org/ISyncSystemService/UpdateVehicleLocationResponse")]
        System.Threading.Tasks.Task<GpsMemService.VehicleLocationResponse> UpdateVehicleLocationAsync(GpsMemService.VehicleLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSystemService/UpdateVehicleExtend", ReplyAction="http://tempuri.org/ISyncSystemService/UpdateVehicleExtendResponse")]
        System.Threading.Tasks.Task<GpsMemService.VehicleExtendResponse> UpdateVehicleExtendAsync(GpsMemService.VehicleExtendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSystemService/ResetIndexVehicle", ReplyAction="http://tempuri.org/ISyncSystemService/ResetIndexVehicleResponse")]
        System.Threading.Tasks.Task<GpsMemService.VehicleIndexResponse> ResetIndexVehicleAsync(GpsMemService.VehicleIndexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSystemService/SetLock", ReplyAction="http://tempuri.org/ISyncSystemService/SetLockResponse")]
        System.Threading.Tasks.Task<bool> SetLockAsync(int xnCode, string label, bool isLock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSystemService/SetDelete", ReplyAction="http://tempuri.org/ISyncSystemService/SetDeleteResponse")]
        System.Threading.Tasks.Task<bool> SetDeleteAsync(int xnCode, string vehiclePlate, bool isDelete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSystemService/SetApproved", ReplyAction="http://tempuri.org/ISyncSystemService/SetApprovedResponse")]
        System.Threading.Tasks.Task<bool> SetApprovedAsync(int xnCode, string vehiclePlate, bool isApproved);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSystemService/Ping", ReplyAction="http://tempuri.org/ISyncSystemService/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSystemService/ChangeVehicled", ReplyAction="http://tempuri.org/ISyncSystemService/ChangeVehicledResponse")]
        System.Threading.Tasks.Task<bool> ChangeVehicledAsync(int xnCode, string vehiclePlace);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSystemService/ChangeVehicleGroup", ReplyAction="http://tempuri.org/ISyncSystemService/ChangeVehicleGroupResponse")]
        System.Threading.Tasks.Task<bool> ChangeVehicleGroupAsync(int xnCode, string vehiclePlate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncSystemService/AddOrEditVehiclesOnline", ReplyAction="http://tempuri.org/ISyncSystemService/AddOrEditVehiclesOnlineResponse")]
        System.Threading.Tasks.Task<bool> AddOrEditVehiclesOnlineAsync(GpsMemService.VehilceOnlineRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ISyncSystemServiceChannel : GpsMemService.ISyncSystemService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SyncSystemServiceClient : System.ServiceModel.ClientBase<GpsMemService.ISyncSystemService>, GpsMemService.ISyncSystemService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SyncSystemServiceClient() : 
                base(SyncSystemServiceClient.GetDefaultBinding(), SyncSystemServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_ISyncSystemService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SyncSystemServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SyncSystemServiceClient.GetBindingForEndpoint(endpointConfiguration), SyncSystemServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SyncSystemServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SyncSystemServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SyncSystemServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SyncSystemServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SyncSystemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<GpsMemService.VehicleOnlineResponse> InitOnlineVerhicleAsync(GpsMemService.VehilceOnlineRequest request)
        {
            return base.Channel.InitOnlineVerhicleAsync(request);
        }
        
        public System.Threading.Tasks.Task<GpsMemService.VehicleOnlineResponse> GetOnlineVerhicleAsync(GpsMemService.VehilceOnlineRequest request)
        {
            return base.Channel.GetOnlineVerhicleAsync(request);
        }
        
        public System.Threading.Tasks.Task<GpsMemService.VehicleOnlineResponse> GetSynOnlineVehicleAsync(GpsMemService.VehilceOnlineRequest request)
        {
            return base.Channel.GetSynOnlineVehicleAsync(request);
        }
        
        public System.Threading.Tasks.Task<GpsMemService.VehicleOnlineResponse> GetOneOnlineVerhicleAsync(GpsMemService.VehilceOnlineRequest request)
        {
            return base.Channel.GetOneOnlineVerhicleAsync(request);
        }
        
        public System.Threading.Tasks.Task<GpsMemService.VehicleLocationResponse> UpdateVehicleLocationAsync(GpsMemService.VehicleLocationRequest request)
        {
            return base.Channel.UpdateVehicleLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<GpsMemService.VehicleExtendResponse> UpdateVehicleExtendAsync(GpsMemService.VehicleExtendRequest request)
        {
            return base.Channel.UpdateVehicleExtendAsync(request);
        }
        
        public System.Threading.Tasks.Task<GpsMemService.VehicleIndexResponse> ResetIndexVehicleAsync(GpsMemService.VehicleIndexRequest request)
        {
            return base.Channel.ResetIndexVehicleAsync(request);
        }
        
        public System.Threading.Tasks.Task<bool> SetLockAsync(int xnCode, string label, bool isLock)
        {
            return base.Channel.SetLockAsync(xnCode, label, isLock);
        }
        
        public System.Threading.Tasks.Task<bool> SetDeleteAsync(int xnCode, string vehiclePlate, bool isDelete)
        {
            return base.Channel.SetDeleteAsync(xnCode, vehiclePlate, isDelete);
        }
        
        public System.Threading.Tasks.Task<bool> SetApprovedAsync(int xnCode, string vehiclePlate, bool isApproved)
        {
            return base.Channel.SetApprovedAsync(xnCode, vehiclePlate, isApproved);
        }
        
        public System.Threading.Tasks.Task<string> PingAsync()
        {
            return base.Channel.PingAsync();
        }
        
        public System.Threading.Tasks.Task<bool> ChangeVehicledAsync(int xnCode, string vehiclePlace)
        {
            return base.Channel.ChangeVehicledAsync(xnCode, vehiclePlace);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeVehicleGroupAsync(int xnCode, string vehiclePlate)
        {
            return base.Channel.ChangeVehicleGroupAsync(xnCode, vehiclePlate);
        }
        
        public System.Threading.Tasks.Task<bool> AddOrEditVehiclesOnlineAsync(GpsMemService.VehilceOnlineRequest request)
        {
            return base.Channel.AddOrEditVehiclesOnlineAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_ISyncSystemService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_ISyncSystemService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://192.168.1.49:2085/SyncServices/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SyncSystemServiceClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_ISyncSystemService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SyncSystemServiceClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_ISyncSystemService);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_ISyncSystemService,
        }
    }
}
